### PR TITLE
fix: incorrect style precedence in editor

### LINKED ISSUE #378: Incorrect style precedence in editor
In the following situation, the editor displays the wrong style in the component menu, although the renderer is correct:

- Style is set in default breakpoint via component styles
- Style is set in lower priority breakpoint via mixin
- Renderer uses default breakpoint style, but editor shows mixin style

https://github.com/samatechtw/pubstudio-builder/assets/550982/ddef1c60-d81d-4b89-97b0-400457b7acea

### PR DESCRIPTION
**Pull request by abemscac**
Close #378

### CODE REVIEW

File: libs/frontend/util-component/src/lib/compute-component-flattened-styles.ts [hunk 1]
```diff
@@ -51,10 +54,19 @@ export const computeComponentFlattenedStyles = (
...
-        ;(result[css as Css] as IRawStyleWithSource).sourcePseudoClass =
-          currentPseudoClass
+      const key = css as Css
+      // Only update the result when the source type is component custom style
+      // since custom style has higher priority, or when the existing entry is
+      // not from component custom style.
+      if (
+        source.sourceType === StyleSourceType.Custom ||
+        result[key]?.sourceType !== StyleSourceType.Custom
+      ) {
```
Comment (abemscac) [inline libs/frontend/util-component/src/lib/compute-component-flattened-styles.ts:64]: This seems to fix the issue. Custom styles always have the highest precedence than any other styles while flattening the styles.
