### PR TITLE
fix: links not working in live site #167

### LINKED ISSUE #167: Links not working in live site
External links no longer work in the live site, see: https://my-subdomain.stg.pubstud.io/home

It appears to be caused by this error:

> DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://linkedin.com/' cannot be created in a document with origin 'http://user1-subdomain.dev.pubstud.io:3000' and URL 'http://user1-subdomain.dev.pubstud.io:3000/home'.
    at O (http://user1-subdomain.dev.pubstud.io:3000/:15:82346)
    at Object.d [as push] (http://user1-subdomain.dev.pubstud.io:3000/:15:81715)
    at f (http://user1-subdomain.dev.pubstud.io:3000/:15:77577)
    at http://user1-subdomain.dev.pubstud.io:3000/:15:74928
    at lt (http://user1-subdomain.dev.pubstud.io:3000/:15:28924)
    at Ce (http://user1-subdomain.dev.pubstud.io:3000/:15:29002)
    at HTMLAnchorElement.n (http://user1-subdomain.dev.pubstud.io:3000/:15:72891)

### PR DESCRIPTION
**Pull request by sampullman**
Close #167

### CODE REVIEW

File: libs/frontend/util-router/src/components/RouterLink.vue [hunk 1]
```diff
@@ -67,11 +67,15 @@ const isExactActive = computed(() => {
   return lastMatch?.name === targetRoute.value?.name
 })
 
-const navigate = () => {
-  if (replace.value) {
-    router.replace(to.value)
-  } else {
-    router.push(to.value)
+const navigate = (e: Event) => {
+  const isExternal = /^(https?:\/\/|www\.)/.test(to.value.path ?? '')
```
Comment (sampullman) [inline libs/frontend/util-router/src/components/RouterLink.vue:71]: @abemscac This is a quick hack to fix the issue. There's probably a better way, but it seems straightforward enough to let the `<a>` proceed naturally (e.g. no `preventDefault`) if the link starts with `http` or `www`.
