### PR TITLE
fix: drag drop into container red outline

### LINKED ISSUE #313: Drag/drop into container red outline
Dragging and dropping a component into a container results in the red highlight remaining visible.

It seems to clear if another component is dragged.

https://github.com/samatechtw/pubstudio-builder/assets/550982/c268290a-f0f2-4647-b20b-623383f68d36

### PR DESCRIPTION
**Pull request by abemscac**
Close #313

### CODE REVIEW

File: libs/frontend/ui-build/src/components/BuildDndOverlay.vue [hunk 1]
```diff
@@ -95,7 +95,8 @@ const hoverOverlayStyle = computed(() => {
       return {
         top: `${top}px`,
         left: `${left}px`,
-        width: `${width}px`,
+        // -1 to prevent horizontal scrollbar from showing up.
+        width: `${width - 1}px`,
```
Comment (abemscac) [inline libs/frontend/ui-build/src/components/BuildDndOverlay.vue:99]: I noticed there'll be a horizontal scrollbar at the bottom when the hover overlay is visible:

https://github.com/samatechtw/pubstudio-builder/assets/59676941/3586fa30-5087-4d4e-b174-fe8af946e90c

I couldn't remember seeing this before 🤔. The `-1` here seems to fix it, and is not too noticeable.

Comment (sampullman) [reply libs/frontend/ui-build/src/components/BuildDndOverlay.vue:99]: Good catch!

**Comment by sampullman** [comment]
👍 🙏
