### PR TITLE
fix: tab to select next component

### LINKED ISSUE #158: Fix tab to select next component
Pressing the tab key when a component is selected in the editor should select the next component (or child component). Currently, only shift-tab is working.

When a text component is selected, but ProseMirror editor is not active, tab should also select the next component. Currently it activates the ProseMirror editor.

### PR DESCRIPTION
**Pull request by abemscac**
Close #158

### CODE REVIEW

File: libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts [hunk 1]
```diff
@@ -229,6 +229,9 @@ export const BuilderDndComponent = defineComponent({
         // TODO -- is this necessary?
         key: renderKey.value,
         ref: dnd.elementRef,
+        // Make builder dnd component not tab-focusable to avoid jumping between
+        // activeElement and component when on Tab press.
+        tabindex: '-1',
```
Comment (abemscac) [inline libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts:234]: Hi @sampullman 

This attribute was added because an element will be focused on mouse click, and that seemed to interfere the tab navigation feature in the builder. Without this attribute the builder would jump between activeElement and the next component when Tab is pressed.

https://github.com/samatechtw/pubstudio-builder/assets/59676941/6b60fdd9-aa2e-446f-a5fd-827d3ea1bdf1

File: libs/frontend/ui-build/src/components/component-menu/ComponentDimensions.vue [hunk 2]
```diff
@@ -135,6 +135,22 @@ const toggleCollapse = () => {
   )
 }
 
+const updateStyle = (property: Css, value: string | undefined) => {
```
Comment (abemscac) [inline libs/frontend/ui-build/src/components/component-menu/ComponentDimensions.vue:138]: This is to fix an issue where jumping to the next size input by pressing Tab would directly update the style of the selected component.

https://github.com/samatechtw/pubstudio-builder/assets/59676941/8262f6df-808b-43ad-898f-12ab216c779a

File: libs/frontend/ui-build/src/components/component-menu/SizeInput.vue [hunk 3]
```diff
@@ -59,6 +61,13 @@ const emit = defineEmits<{
   (e: 'update', size: string | undefined): void
 }>()
 
+// Set tabindex to -1 when right menu is not focused to make size input not tab-focusable when
+// right menu is not focused. In the builder, we can select the next component by pressing Tab
+// continuously. However, if the next component is currently not in the viewport, after the
+// scrollToComponent operation, the subsequent Tab press will focus on the first size input
+// instead of selecting the next component.
+const tabIndex = computed(() => (runtimeContext.rightMenuFocused.value ? 1 : -1))
```
Comment (abemscac) [inline libs/frontend/ui-build/src/components/component-menu/SizeInput.vue:69]: There's a strange behavior I don't understand; if the next component is in the viewport, pressing Tab would correctly select & gain focus on the next component. But if the next component is not in the viewport, after the scrollToComponent operation, the subsequent Tab press will focus on the first size input (probably because inputs are tab-focusable?) instead of selecting the next component.

https://github.com/samatechtw/pubstudio-builder/assets/59676941/a25709b5-d1a8-4657-a7d0-a362c9d028fa

Unfortunately, I didn't a clean way to solve this problem 😕. My current workaround is to only enable the tab navigation of size inputs when right menu is focused.

File: libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts (hunk 1 above)
Comment (sampullman) [reply libs/frontend/feature-render-builder/src/lib/dnd/builder-dnd-component.ts:234]: 👍

File: libs/frontend/ui-build/src/components/component-menu/SizeInput.vue (hunk 3 above)
Comment (sampullman) [reply libs/frontend/ui-build/src/components/component-menu/SizeInput.vue:69]: I see! I guess that's just how the browser handles the tab key normally. Your fix seems to work well 🙏

**Comment by sampullman** [comment]
Looks good to me!
