### PR TITLE
78 color picker theme

### LINKED ISSUE #78: Select theme variable in color picker
Use selected theme variable instead of color, in color picker. For example, if `color-text` is chosen, set the corresponding CSS to `${color-text}` instead of the RGBA/hex value.

### LINKED ISSUE #94: Can't type in reusable style menu
Typing a name in the edit reusable style menu doesn't work.

### PR DESCRIPTION
**Pull request by sampullman**
Close #78 
Close #94

### CODE REVIEW

**Comment by sampullman** [comment]
@abemscac In this PR I added support for theme variables in the color picker. I'll leave some comments in the code, this was more complicated than I expected, especially with gradients, so there's a good chance some bugs were introduced.

It should support:
- Set color to theme var
- Undo works as expected
- Set any gradient stop as theme var
- Edit a gradient with theme vars

File: libs/frontend/feature-build/src/components/build-render/ProseMirrorEditor.vue [hunk 1]
```diff
@@ -70,7 +71,10 @@ const gradientColorStyle = computed(() => {
     activeBreakpoint.value,
   )
 
-  const background = gradientColorStyles[Css.Background]
+  const background = resolveThemeVariables(
```
Comment (sampullman) [inline libs/frontend/feature-build/src/components/build-render/ProseMirrorEditor.vue:74]: Now the prosemirror style has to resolve theme variables in the background color.

File: libs/frontend/feature-build/src/components/toolbar/ToolbarColorPicker.vue [hunk 2]
```diff
@@ -8,18 +8,28 @@
...
 import { IThemeVariable } from '@pubstudio/shared/type-site'
-import ToolbarItem from './ToolbarItem.vue'
+import { IThemedGradient } from '@pubstudio/frontend/util-gradient'
+import { resolveThemeVariables } from '@pubstudio/frontend/util-builtin'
+import { ToolbarItem } from '@pubstudio/frontend/ui-widgets'
+import { useBuild } from '../../lib/use-build'
+
+const { site } = useBuild()
+
+const resolveThemeVar = (themeVar: string): string | undefined => {
```
Comment (sampullman) [inline libs/frontend/feature-build/src/components/toolbar/ToolbarColorPicker.vue:30]: To avoid `ColorPicker` dependency on `use-build`, I pass in a function to resolve theme variables.

File: libs/frontend/feature-build/src/components/toolbar/ToolbarColorPicker.vue [hunk 3]
```diff
@@ -38,7 +48,7 @@ withDefaults(
 )
 const emit = defineEmits<{
   (e: 'click', event: Event): void
-  (e: 'selectColor', color: IRgba): void
-  (e: 'applyGradient', gradient: string): void
+  (e: 'selectColor', color: IPickerColor): void
+  (e: 'applyGradient', gradient: IThemedGradient): void
```
Comment (sampullman) [inline libs/frontend/feature-build/src/components/toolbar/ToolbarColorPicker.vue:52]: I pass `IThemedGradient` everywhere instead of `string`, the only difference is it also stores the un-resolved value (with theme variables).

This was done before I added `resolveThemeVar` to the `ColorPicker` props, so it may be possible to compute it on the fly, instead of storing both values 🤔

File: libs/frontend/feature-build/src/components/toolbar/ToolbarContainer.vue [hunk 4]
```diff
@@ -27,8 +27,8 @@
       <SizeDropdown />
       <ToolbarColorPicker
         :tooltip="t('style.toolbar.background_color')"
-        :color="getStyleValue(Css.BackgroundColor)"
-        :gradient="getStyleValue(Css.Background)"
+        :color="getRawStyle(Css.BackgroundColor)"
```
Comment (sampullman) [inline libs/frontend/feature-build/src/components/toolbar/ToolbarContainer.vue:30]: The original style with theme variables is passed to the color picker now, so I added a function to get the style without resolving theme.

File: libs/frontend/feature-build/src/lib/use-toolbar.ts [hunk 5]
```diff
@@ -74,15 +83,23 @@ export const useToolbar = (): IUseToolbar => {
...
     newValue: string | undefined,
-  ): ICommand<ISetComponentCustomStyleData> => {
+  ): ICommand<ISetComponentCustomStyleData> | undefined => {
     const { selectedComponent } = editor.value ?? {}
     if (!selectedComponent) {
       throw new Error(
         'Cannot create set component custom style command when no component is selected',
       )
     }
+    const oldStyle = selectedComponentFlattenedStyles.value[property]
```
Comment (sampullman) [inline libs/frontend/feature-build/src/lib/use-toolbar.ts:94]: Previously, `createSetComponentCustomStyleCommand` accepted the oldValue, and we were passing in the old style after resolving theme variables. This caused a problem with undo, since changing a themed color, then undoing, would result in the resolved color instead of the variables.

File: libs/frontend/feature-color-picker/src/lib/compute-gradient.ts [hunk 6]
```diff
@@ -1,47 +1,37 @@
...
+        const v = themeVar ? `$\{${themeVar}}` : undefined
+        return `${v ?? rgba} ${stop}%`
+      })
+      .join(',')
+  }
 
-  return `${gradientType}(${degree}${colors})`
-}
-
-export const computeRadialGradient = (
```
Comment (sampullman) [inline libs/frontend/feature-color-picker/src/lib/compute-gradient.ts:21]: I noticed all these `computeXGradient` functions were the same, so I combined them. Hopefully that's correct 😅

File: libs/frontend/feature-color-picker/src/lib/compute-gradient.ts [hunk 7]
```diff
@@ -1,47 +1,37 @@
...
 
-  const colors = [...gradientColors]
-    .sort((a, b) => a.stop - b.stop)
+  const colors = sorted
     .map((gradientColor) => {
       const { rgba, stop } = gradientColor
       return `${rgba} ${stop}%`
     })
     .join(',')
+  const hasThemeVar = sorted.some((c) => !!c.themeVar)
```
Comment (sampullman) [inline libs/frontend/feature-color-picker/src/lib/compute-gradient.ts:21]: Add theme variable parsing to `computeGradient`

File: libs/frontend/util-gradient/src/lib/parse-gradients.ts [hunk 8]
```diff
@@ -35,6 +42,50 @@ export const parseGradientColors = (gradient: string | undefined): IGradientColo
         }
       }
     }
+    // Parse hex
+    const hexMatches = gradient.matchAll(/#.*?%/g)
```
Comment (sampullman) [inline libs/frontend/util-gradient/src/lib/parse-gradients.ts:46]: Support hex colors in gradients

File: libs/frontend/util-gradient/src/lib/parse-gradients.ts [hunk 9]
```diff
@@ -35,6 +42,50 @@ export const parseGradientColors = (gradient: string | undefined): IGradientColo
...
+          const rgba = `rgba(${c.r},${c.g},${c.b})`
+          gradientColors.push({
+            rgba,
+            stop: parseInt(stop || '0'),
+          })
+        }
+      }
+    }
+    // Parse theme variables
+    const varMatches = gradient.matchAll(/\$\{.*?\}.*?%/g)
```
Comment (sampullman) [inline libs/frontend/util-gradient/src/lib/parse-gradients.ts:65]: Support theme vars in gradients

File: libs/frontend/feature-color-picker/src/lib/compute-gradient.ts (hunk 6 above)
Comment (abemscac) [reply libs/frontend/feature-color-picker/src/lib/compute-gradient.ts:21]: Yeah, I think it's correct! Thanks!
