### PR TITLE
fix: publish site cache bug #368

### LINKED ISSUE #368: Publishing new site fails
Publishing a new site (without a draft) doesn't always work.

- Reproduce bug and add failing test case
- Determine cause and fix

### PR DESCRIPTION
**Pull request by sampullman**
Close #368

### CODE REVIEW

File: backend/lib-shared-site-api/src/cache/cache.rs [hunk 1]
```diff
@@ -263,4 +243,24 @@ impl AppCache {
     pub async fn remove_metadata(&self, site_id: &str) {
         self.metadata_cache.invalidate(site_id).await;
     }
+
+    // Site Data
+    pub async fn get_site_with(
```
Comment (sampullman) [inline backend/lib-shared-site-api/src/cache/cache.rs:248]: @ClaireMao1996 I ended up splitting the site data cache from usage. There were some bugs in publishing and creating drafts, and I think the code is a little easier to follow this way. Instead of updating the cache when the site data changes, we can just clear it and let `get_current_site` refresh it when needed.
