### PR TITLE
fix: css pseudostyle editor bug

### LINKED ISSUE #66: CSS pseudostyle editor bug
When a non-default pseudo style is selected in the editor, all the normal stylings disappear.

https://github.com/samatechtw/pubstudio-builder/assets/550982/96f6843f-861c-4640-81b5-b31e047de303

### PR DESCRIPTION
**Pull request by abemscac**
Close #66

### CODE REVIEW

File: libs/frontend/ui-widgets/src/lib/InfoBubble.vue [hunk 1]
```diff
@@ -131,6 +131,7 @@ const hideBubble = () => {
   @mixin size 20px;
   cursor: pointer;
   position: relative;
+  flex-shrink: 0;
```
Comment (abemscac) [inline libs/frontend/ui-widgets/src/lib/InfoBubble.vue:134]: Hi @sampullman 

I noticed that the inherited from info bubble is invisible when style row is too wide, so I add `flex-shrink: 0` here to make it visible again.

Screenshot 2023-11-17 at 5 55 14 PM

Comment (sampullman) [reply libs/frontend/ui-widgets/src/lib/InfoBubble.vue:134]: Thanks! I think there are probably a few more similar bugs here and there.
