### PR TITLE
fix: breakpoint styles incorrect in editor #273

### LINKED ISSUE #273: Breakpoint styles not displaying correctly in editor
Breakpoint, and possibly mixin styles, are not displaying correctly in the editor.

See this example site, selecting either the Mobile or Tablet(Small) breakpoints displays the site incorrectly, although preview/live works as expected:

[240126_blog-company-3.json](https://github.com/samatechtw/pubstudio-builder/files/14073245/240126_blog-company-3.json)

### PR DESCRIPTION
**Pull request by sampullman**
Close #273

### CODE REVIEW

File: libs/frontend/feature-render-builder/src/lib/compute-builder-reusable-styles.ts [hunk 1]
```diff
@@ -14,10 +14,10 @@ export const computeBuilderReusableStyles = (site: ISite): IRawStyleRecord => {
   const accumulatedBreakpointIds = new Set<string>([DEFAULT_BREAKPOINT_ID])
 
   for (const breakpoint of descSortedBreakpoints.value) {
+    accumulatedBreakpointIds.add(breakpoint.id)
```
Comment (sampullman) [inline libs/frontend/feature-render-builder/src/lib/compute-builder-reusable-styles.ts:17]: @abemscac I had to move this line above the `activeBreakpoint`, otherwise the current breakpoint wouldn't be added.

File: libs/frontend/feature-render-builder/src/lib/compute-builder-reusable-styles.ts [hunk 2]
```diff
@@ -28,13 +28,18 @@ export const computeBuilderReusableStyles = (site: ISite): IRawStyleRecord => {
     accumulatedBreakpointIds.forEach((breakpointId) => {
       const bpStyle = style.breakpoints[breakpointId]
       const rawStyle = bpStyle?.[CssPseudoClass.Default] ?? {}
-      result[`.${styleId}`] = { ...rawStyle }
+      const cls = `.${styleId}`
+      const currentStyle = result[cls] ?? {}
+      result[cls] = { ...currentStyle, ...rawStyle }
```
Comment (sampullman) [inline libs/frontend/feature-render-builder/src/lib/compute-builder-reusable-styles.ts:33]: @abemscac Instead of replacing the style, I think we need to merge. Otherwise styles from larger breakpoints aren't applied in the builder. This change was also necessary in `getBuildPageStyle`.

File: libs/frontend/feature-render-builder/src/lib/compute-builder-reusable-styles.ts [hunk 3]
```diff
@@ -14,10 +14,10 @@ export const computeBuilderReusableStyles = (site: ISite): IRawStyleRecord => {
   const accumulatedBreakpointIds = new Set<string>([DEFAULT_BREAKPOINT_ID])
```
Comment (sampullman) [inline libs/frontend/feature-render-builder/src/lib/compute-builder-reusable-styles.ts:14]: I think we're relying on the ordering of the set, which is not good. It's probably better to make this an array, there shouldn't be any downside. Also, it can be moved out of the `appendStyle` for efficiency, since we only need to calculate the `accumulatedBreakpointIds` once per render.

I'll submit a separate PR with these changes to see if everything still works!
