### PR TITLE
fix: prosemirror up/down skips blank lines

### LINKED ISSUE #172: ProseMirror up/down skips blank lines
Up and down keys skip blank lines in the ProseMirror editor.

https://github.com/samatechtw/pubstudio-builder/assets/550982/a937f8e3-6c88-4635-bb8e-147e49d4d7a4

### PR DESCRIPTION
**Pull request by abemscac**
Close #172 

Hi @sampullman 

I think it's finally solved! Turns out the bug is actually caused by one of the default browser behavior instead of ProseMirror.
The same issue can be observed in [this sandbox](https://stackblitz.com/edit/web-platform-egfkum?file=index.html). It seems that `p::after { content: '\200b'; }` with a `<br>` inside will be skipped when using keyboard navigation; the only way to set the cursor to these "empty" lines is clicking them with mouse.

If I remember correctly, `p::after { content: '\200b'; }` was added because empty `<p></p>` will collapse when ProseMirror editor is not active. So I modify the style of `.pm-p` here and there to make sure `::after { content: '\200b'; }` is only applied when the component is not selected (for builder), and when in Preview Page & web-site app.

### CODE REVIEW

File: libs/frontend/feature-preview/src/lib/preview-component.ts [hunk 1]
```diff
@@ -31,11 +31,11 @@ export const PreviewComponent = () => {
     setup(props: ILiveComponentProps) {
       const { site, component } = toRefs(props)
       const { custom } = computeEvents(site.value, component.value)
-      registerCustomEvents(component.value, custom, null, true)
+      registerCustomEvents(component.value, custom, null, false)
 
       onMounted(() => {
         const { custom } = computeEvents(site.value, component.value)
-        registerCustomEvents(component.value, custom, null, false)
+        registerCustomEvents(component.value, custom, null, true)
```
Comment (abemscac) [inline libs/frontend/feature-preview/src/lib/preview-component.ts:38]: I noticed that if we use `document.getElementById(componentId)` in the appear event of a component, it always return `null`. I think the `true` and `false` here should be swapped.

File: libs/frontend/feature-template/project.json [hunk 2]
```diff
@@ -1,5 +1,5 @@
 {
-  "name": "frontend-feature-template",
+  "name": "frontend-feature-template-builder",
```
Comment (abemscac) [inline libs/frontend/feature-template/project.json:2]: I added the `-builder` suffix to the `name` of some of the `project.json` in `pubstudio/pubstudio-builder` 
 because there are some project name conflicts between `pubstudio/libs` and `pubstudio/pubstudio-builder/libs`, otherwise Nx will throw an error when executing commands like `npx nx serve web`.

Screenshot 2024-01-23 at 3 44 59 PM

File: libs/frontend/feature-preview/src/lib/preview-component.ts (hunk 1 above)
Comment (sampullman) [reply libs/frontend/feature-preview/src/lib/preview-component.ts:38]: Makes sense to me, but I wonder if it's a mistake or there was some other reason 🤔 
I'll keep an eye out!

File: libs/frontend/feature-template/project.json (hunk 2 above)
Comment (sampullman) [reply libs/frontend/feature-template/project.json:2]: That should be fine! In theory we should also update the folder name and references, otherwise some NX commands might get confused. But in this case I think there's a low chance we'll need to use NX commands on the library, so this is a good solution.

File: libs/frontend/ui-theme/src/css/components/prosemirror-view.postcss [hunk 3]
```diff
@@ -34,9 +34,6 @@
 .ProseMirror pre {
   white-space: pre-wrap;
 }
-.ProseMirror-trailingBreak {
```
Comment (sampullman) [inline libs/frontend/ui-theme/src/css/components/prosemirror-view.postcss:37]: I think the reason why this was removed is that it results in extra spaces int the editor that don't exist in preview/live mode. You can see the difference when you press enter in the ProseMirror editor.

**Comment by sampullman** [comment]
The explanation makes sense, but doesn't seem to be working as expected. Pressing the down arrow works to select the empty line, but pressing down again sends the cursor to the end of the editor:


https://github.com/samatechtw/pubstudio-builder/assets/550982/48f93def-44ff-45c5-a013-a2553e5e0168

**Comment by abemscac** [comment]
Oh, sorry about that! It seems to work on my end 😬: 

https://github.com/samatechtw/pubstudio-builder/assets/59676941/cbdb8c9a-25f4-41c0-86ce-f6d0c5fe3168

I wonder if the behavior is observed because of some missing code in the `pubstudio` repo; there are some changes made to the `App.vue` inside that repository, so we have to checkout to `172-prosemirror-up-down-skips-blank-lines` in both repos to really fix the bug.

**Comment by sampullman** [comment]
You're right! I thought I was on the correct branch, but must have switched before I tested.
